server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /dashboard-hidroponik/ {
    try_files $uri $uri/ /dashboard-hidroponik/index.html;
  }

  location / {
    return 301 /dashboard-hidroponik/;
  }
}
